import { useState } from "react";
import { C, TABS } from "../constants";
import type { FormData, TabId } from "../types";
import { TabBar } from "./TabBar";
import { PlanContent } from "./PlanContent";
import { markdownToHtml } from "../lib/markdown";

interface Props {
  form: FormData;
  content: Partial<Record<TabId, string>>;
  onRetry: (tabId: TabId) => void;
  onReset: () => void;
}

const STEPS = [
  "✅ Study your target market",
  "✅ Register with DTI / SEC",
  "✅ Get your Mayor's Permit",
  "✅ Open a business bank account",
  "✅ Find your suppliers",
  "✅ Set up your social media",
  "✅ Create your opening promos",
  "✅ Test your product or service",
  "✅ Get your first customers",
  "✅ Track your finances daily",
];

export function ResultView({ form, content, onRetry, onReset }: Props) {
  const [activeTab, setActiveTab] = useState<TabId>("overview");

  const exportPlan = () => {
    const sections = TABS.map((tab) => {
      const c = content[tab.id] ?? "This section was not generated.";
      const html = markdownToHtml(c.startsWith("__") ? "This section was not generated." : c);
      return `
        <section class="section">
          <div class="section-header">
            <span class="section-icon">${tab.icon}</span>
            <h2 class="section-title">${tab.label}</h2>
          </div>
          <div class="section-body">${html}</div>
        </section>`;
    }).join("\n");

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>Business Plan – ${form.business}</title>
<link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@600;700&family=Playfair+Display:ital,wght@0,700;1,400&family=DM+Sans:wght@300;400;600&display=swap" rel="stylesheet"/>
<style>
*{box-sizing:border-box;margin:0;padding:0;}
:root{--bg:#EDE0CC;--card:#FAF4E8;--border:#DDD0B0;--brown:#2C1A0E;--mid:#7A4A18;--light:#B89060;--gold:#C9A84C;--accent:#B87A30;--dark:#160802;}
body{background:var(--bg);font-family:'DM Sans',sans-serif;color:var(--brown);padding:40px 20px;}
.container{max-width:800px;margin:0 auto;}
h1{font-family:'Playfair Display',serif;font-size:42px;color:var(--brown);margin-bottom:12px;}
.subtitle{font-style:italic;color:var(--accent);margin-bottom:40px;}
.section{margin-bottom:48px;background:white;padding:32px;border-radius:16px;box-shadow:0 2px 8px rgba(0,0,0,0.05);}
.section-header{display:flex;align-items:center;gap:12px;margin-bottom:20px;padding-bottom:12px;border-bottom:2px solid var(--gold);}
.section-icon{font-size:24px;}
.section-title{font-family:'Playfair Display',serif;font-style:italic;font-size:22px;color:var(--mid);}
.section-body{font-size:14px;line-height:1.8;color:#3A1E08;}
.section-body h1,.section-body h2,.section-body h3{font-family:'Playfair Display',serif;font-style:italic;color:#5C3010;margin:16px 0 8px;}
.section-body h1{font-size:18px;}.section-body h2{font-size:16px;}.section-body h3{font-size:14px;}
.section-body p{margin:8px 0;}.section-body ul,.section-body ol{padding-left:24px;margin:12px 0;}
.section-body li{margin-bottom:6px;}.section-body strong{color:var(--brown);font-weight:700;}
.section-body table{width:100%;border-collapse:collapse;margin:20px 0;background:white;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(44,26,14,0.08);}
.section-body thead tr{background:linear-gradient(135deg,#1a0800,#2C1A0E);}
.section-body th{padding:14px 16px;text-align:left;color:#EDE0CC;font-weight:600;font-size:14px;border-bottom:2px solid #C9A84C;}
.section-body tbody tr:nth-child(odd){background:#FAF8F5;}.section-body tbody tr:nth-child(even){background:#FFFFFF;}
.section-body tbody tr{border-bottom:1px solid #EDE0CC;}
.section-body td{padding:12px 16px;color:#3A1E08;font-size:14px;line-height:1.6;}
</style>
</head>
<body>
<div class="container">
<h1>${form.business}</h1>
<p class="subtitle">Business Plan · DisenyoDigitals</p>
${sections}
<div style="margin-top:60px;text-align:center;color:var(--light);font-size:12px;">
  <p>Generated by DisenyoDigitals Business Plan Studio</p>
  <p>For Filipino entrepreneurs 💛</p>
</div>
</div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `BusinessPlan-${form.business.replace(/\s+/g, "")}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="result-view" style={{ maxWidth: 960, width: "100%", padding: "30px 24px 64px", boxSizing: "border-box" }}>
      {/* Success header */}
      <div className="card" style={{ padding: "32px 28px", textAlign: "center", marginBottom: 18 }}>
        <div style={{ fontSize: 40 }}>🎉</div>
        <h1
          className="result-title"
          style={{
            fontSize: 32,
            fontFamily: "'Playfair Display',serif",
            fontWeight: 700,
            color: C.brown,
            marginBottom: 8,
          }}
        >
          Your <em style={{ color: C.accent, fontStyle: "italic" }}>Business Plan</em> is Ready!
        </h1>
        <p style={{ fontSize: 14, color: C.mid, fontStyle: "italic", marginBottom: 20 }}>
          <strong style={{ color: C.gold }}>{form.business}</strong> · {form.location}
        </p>
        <div className="result-actions">
          <button
            onClick={onReset}
            className="btn btn-secondary"
            style={{ padding: "11px 20px", fontSize: 13 }}
          >
            ← Start Over
          </button>
          <button
            onClick={exportPlan}
            className="btn btn-primary"
            style={{ padding: "11px 22px", fontSize: 13 }}
          >
            ⬇ Download Plan (HTML)
          </button>
        </div>
      </div>

      <TabBar activeTab={activeTab} content={content} onSelect={setActiveTab} />
      <PlanContent activeTab={activeTab} content={content} onRetry={onRetry} />

      {/* Quick-start steps */}
      <div
        style={{
          background: `${C.gold}10`,
          border: `1px solid ${C.gold}40`,
          borderRadius: 20,
          padding: "24px 28px",
          marginTop: 18,
        }}
      >
        <h3
          style={{
            color: C.mid,
            fontSize: 15,
            fontFamily: "'Playfair Display',serif",
            fontStyle: "italic",
            marginBottom: 14,
          }}
        >
          ✦ 10 Steps to Get Started Today
        </h3>
        <div
          className="steps-grid"
          style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill,minmax(230px,1fr))", gap: 9 }}
        >
          {STEPS.map((item, i) => (
            <div
              key={i}
              className="step-card"
              style={{
                background: C.card,
                borderRadius: 14,
                padding: "10px 14px",
                fontSize: 13,
                color: "#4A2C10",
              }}
            >
              {item}
            </div>
          ))}
        </div>
      </div>

      <div style={{ textAlign: "center", padding: "16px 0", marginTop: 18 }}>
        <p style={{ color: C.light, fontSize: 13, marginBottom: 4 }}>
          Want more help with your business journey?
        </p>
        <strong style={{ color: C.mid, fontSize: 15 }}>Follow us: @DisenyoDigitals 💛</strong>
      </div>
    </div>
  );
}
